<a href="https://colab.research.google.com/github/Bipasha1005/DeepLearning/blob/main/FFNN1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

def sigmoid(x):
  return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
  return x*(1-x)

training_inputs = np.array([[0,0,1],[1,1,1],[1,0,1],[0,1,1]])
print("The inputs are: \n" ,training_inputs)

training_outputs = np.array([[0,1,1,0]]).T
print("The outputs are: \n" ,training_outputs)

np.random.seed(1)

synaptic_weights = 2*np.random.random((3,1))-1
print("The weights are: \n" ,synaptic_weights)

for i in range(100):
  input_layer = training_inputs
  outputs = sigmoid(np.dot(input_layer, synaptic_weights))
  print("Output after training : ", outputs)

error = training_outputs - outputs
print("Error after training: ", error)


The inputs are: 
 [[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]]
The outputs are: 
 [[0]
 [1]
 [1]
 [0]]
The weights are: 
 [[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Output after training :  [[0.2689864 ]
 [0.3262757 ]
 [0.23762817]
 [0.36375058]]
Output after training :  [[0.2689864 ]
 [0.3262757 ]
 [0.23762817]
 [0.36375058]]
Output after training :  [[0.2689864 ]
 [0.3262757 ]
 [0.23762817]
 [0.36375058]]
Output after training :  [[0.2689864 ]
 [0.3262757 ]
 [0.23762817]
 [0.36375058]]
Output after training :  [[0.2689864 ]
 [0.3262757 ]
 [0.23762817]
 [0.36375058]]
Output after training :  [[0.2689864 ]
 [0.3262757 ]
 [0.23762817]
 [0.36375058]]
Output after training :  [[0.2689864 ]
 [0.3262757 ]
 [0.23762817]
 [0.36375058]]
Output after training :  [[0.2689864 ]
 [0.3262757 ]
 [0.23762817]
 [0.36375058]]
Output after training :  [[0.2689864 ]
 [0.3262757 ]
 [0.23762817]
 [0.36375058]]
Output after training :  [[0.2689864 ]
 [0.3262757 ]
 [0.23762817]
 [0.36375058]]
Output after trainin